// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ogryhxpewxkzbsioulfh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ncnloeHBld3hremJzaW91bGZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwOTY0OTgsImV4cCI6MjA3MTY3MjQ5OH0.xzX3UcXMdUaoNsnOtB5PDScdUJMA9IbS9Q5JSSvMHDQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});